# Generated by Django 4.2.1 on 2024-03-01 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysss', '0003_remove_billingaddress_address_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysss.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysss.product')),
            ],
        ),
    ]
