# Generated by Django 4.2.1 on 2024-03-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysss', '0004_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
