# Generated by Django 4.2.1 on 2024-03-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysss', '0008_alter_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='customers',
            field=models.ManyToManyField(blank=True, related_name='cart', to='mysss.customer'),
        ),
    ]
