# Generated by Django 4.2.1 on 2024-04-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysss', '0009_product_customers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='product',
        ),
        migrations.AddField(
            model_name='purchase',
            name='product',
            field=models.ManyToManyField(to='mysss.product'),
        ),
    ]
