# Generated by Django 4.2.1 on 2024-04-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysss', '0010_remove_purchase_product_purchase_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='shipping_address',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
