# Generated by Django 4.2.1 on 2024-04-04 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysss', '0011_purchase_shipping_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='shipping_address',
        ),
    ]
