# Generated by Django 4.2.1 on 2024-04-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysss', '0013_rename_product_purchase_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='card_credentials',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='purchase',
            name='cvc',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='purchase',
            name='expiry_month',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='purchase',
            name='expiry_year',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='purchase',
            name='shipping_address',
            field=models.CharField(default='', max_length=255),
        ),
    ]
