# Generated by Django 4.2.1 on 2024-04-09 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysss', '0015_remove_purchase_card_credentials_remove_purchase_cvc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='purchase_date',
        ),
    ]
