# Generated by Django 4.2.1 on 2024-04-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysss', '0017_purchase_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='card_credentials',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='cvc',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='expiry_month',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='expiry_year',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='shipping_address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
